language: haskell

env:
  - GHCVER=7.8.3

before_install:
  - |
    if [ $GHCVER = `ghc --numeric-version` ]; then
      # Try installing some of the build-deps with apt-get for speed.
      travis/cabal-apt-install --enable-tests
      export CABAL=cabal
    else
      # Install the GHC we want from hvr's PPA
      travis_retry sudo add-apt-repository -y ppa:hvr/ghc
      travis_retry sudo apt-get update
      travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
      export PATH=/opt/ghc/$GHCVER/bin:$PATH
      export CABAL=cabal-1.18
    fi

  - export CABALPRIME=./cabal
  - $CABAL update

install:
  - $CABALPRIME build

script:
  - $CABALPRIME test