[master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20170104233312-ee8addd/master-haskell-20170104233312-ee8addd"
  version = 1
  sha1 = "3b707a2ba2d74ee13fe81a658bed191a5808e6f5"

[build.dist-7-10]
  GHC_VERSION="7.10.2"
  CABAL_VERSION="1.22.4.0"
  ICICLE_CC_OPTIONS = "-Wall -Werror"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
  PUBLISH_EXECUTABLES = "icicle-repl"

[build.dist-8-0]
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"

[build.branches-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"
  ICICLE_CC_OPTIONS = "-Wall -Werror"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_BRANCHES"
  PUBLISH_EXECUTABLES = "icicle-repl"

[build.branches-8-0]
  GHC_VERSION = "8.0.1"
  CABAL_VERSION = "1.24.0.0"

#
# Swadling Territory
#

[build.appshop]
  PUBLISH_APPSHOP = "icicle-repl"

[build.appshop.master]
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell-appshop/linux/x86_64/20170104233312-ee8addd/master-haskell-appshop-20170104233312-ee8addd"
  sha1 = "e60047c69f2578cd3db3ee9582da313e6166baa9"
